name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.27.0
      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: 16
      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright
      - name: Install packages
        run: pnpm install --prefer-offline --frozen-lockfile
      - name: Install playwright chromium browser
        run: pnpx playwright install chromium
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - name: Turbo cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-
      - name: Build
        run: |
          pnpm run build --cache-dir=".turbo"
      - name: build-only
        run: |
          pnpm run build-only --cache-dir=".turbo"
      - name: Start server
        run: | 
          pnpm run start &
          sleep 5
      - name: e2e test
        run: |
          pnpm run ci --cache-dir=".turbo"